### ISSUE TITLE
NullReferenceException when field with 'Expression' type is empty

### ISSUE THREAD

**Issue by dleman** [FrendsPlatform/Frends.SMTP#14]
BUG: Task is throwing "Object reference not set to an instance of an object." error when one of the fields is left empty with type "Expression". Works properly when field type is set up to "Text".

**Comment by julietpaw** [comment]
> BUG: Task is throwing "Object reference not set to an instance of an object." error when one of the fields is left empty with type "Expression". Works properly when field type is set up to "Text".

I'll fix that
