### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/Frends.SMTP#6]
Nuget package missing metadata - ERROR: Metadata file not file (FrendsTaskMetadata.json)

Also check that examples are in docs.

Also check build warnings.

**Comment by ttossavainen** [comment]
https://github.com/FrendsPlatform/Frends.SMTP/pull/13

**Comment by ttossavainen** [comment]
There are directory naming issues that require fix before doing any documentation fixes. Closing this issue for now with no changes done.
